name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    if: github.ref_name != 'v0.0.0'
    uses: libops/.github/.github/workflows/sitectl-plugin-goreleaser.yaml@024b3a35736fd8857c990b5b33fd15c47ac787aa # main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      go-version: "1.26.x"
      package-name: sitectl-app-tmpl
